name: Commit verification

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Run commit verification
      run: |
        pytest linters/
